# Generated by Django 3.2 on 2021-05-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.student', verbose_name='étudiant'),
        ),
    ]
