# Generated by Django 3.2 on 2021-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_attempt_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='étudiant'),
        ),
    ]
